// Export CSS
export const styles = {
  emailFormWindow: {
    width: "100%",
    overflow: "hidden",
    transition: "all 0.5s ease",
    WebkitTransition: "all 0.5s ease",
    MozTransition: "all 0.5s ease",
  },
  stripe: {
    position: "relative",
    top: "-45px",
    width: "100%",
    height: "240px",
    backgroundColor: "#0D5CAB",
    transform: "skewY(-12deg)",
  },
  topText: {
    position: "relative",
    width: "100%",
    top: "5%",
    color: "white",
    fontSize: "14px",
    fontWeight: "600",
  },
  inputOne: {
    width: "66%",
    height: "40px",
    textAlign: "center",
    outline: "none",
    padding: "12px",
    margin: "3px",
    borderRadius: "12px",
    border: "2px solid #0D5CAB",
  },
  inputTwo: {
    width: "66%",
    height: "80px",
    textAlign: "center",
    outline: "none",
    padding: "12px",
    margin: "3px",
    borderRadius: "12px",
    border: "2px solid #0D5CAB",
    overflowX: "none"
  },
  sendButton: {
    width: "66%",
    height: "40px",
    textAlign: "center",
    outline: "none",
    padding: "12px",
    margin: "3px",
    borderRadius: "12px",
    border: "2px solid #0D5CAB",
    color: "#fff",
    backgroundColor: "#0D5CAB",
    cursor: "pointer",
  },
  bottomText: {
    position: "absolute",
    width: "100%",
    top: "72%",
    color: "#0D5CAB",
    fontSize: "14px",
    fontWeight: "600",
  },
  loadingDiv: {
    position: "absolute",
    height: "100%",
    width: "100%",
    textAlign: "center",
    backgroundColor: "white",
  },
  loadingIcon: {
    color: "#7a39e0",
    position: "absolute",
    top: "calc(50% - 51px)",
    left: "calc(50% - 51px)",
    fontWeight: "600",
  },
  chatEngineWindow: {
    width: "100%",
    backgroundColor: "#fff",
  },
};
